//Auth Actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCESS = 'LOGOUT_SUCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const FETCH_USER_DETAILS_SUCESS = 'FETCH_USER_DETAILS_SUCESS';
export const FETCH_USER_DETAILS_FAIL = 'FETCH_USER_DETAILS_FAIL';
