export const FETCH_SHOWS = "FETCH_SHOWS";
export const SEARCH_SHOWS = "SEARCH_SHOWS";
export const CLEAR_SEARCH_SHOWS = "CLEAR_SEARCH_SHOWS";
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_SHOWS_BY_GENRE = "FETCH_SHOWS_BY_GENRE";